// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMS.Infrastructure.Persistence;

#nullable disable

namespace UMS.Infrastructure.Migrations
{
    [DbContext(typeof(UmsDbContext))]
    [Migration("20250227210819_addKeysAndTables")]
    partial class addKeysAndTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UMS.Core.Entities.Role", b =>
                {
                    b.Property<int?>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UMS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("OtpSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<int?>("zone_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UMS.Core.Entities.Zone", b =>
                {
                    b.Property<int?>("zone_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("zone")
                        .HasColumnType("longtext");

                    b.HasKey("zone_id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("UMS.Core.Entities.User", b =>
                {
                    b.HasOne("UMS.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("role_id");

                    b.HasOne("UMS.Core.Entities.Zone", "Zone")
                        .WithMany("Users")
                        .HasForeignKey("role_id");

                    b.Navigation("Role");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("UMS.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UMS.Core.Entities.Zone", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
